// import * as c from "./constants.js"
// import Asset from "./assets/Asset.js"
// import Page from "./assets/Page.js"

import {c, Asset, Page} from "./internal.js"

export const typeMappingArray = new Map([  
    [c.TYPES.ASSETFACTORY, Asset],
    [c.TYPES.ASSETFACTORYCONTAINER, Asset],
    [c.TYPES.CLOUDTRANSPORT, Asset],
    [c.TYPES.CONNECTORCONTAINER, Asset],
    [c.TYPES.CONTENTTYPE, Asset],
    [c.TYPES.CONTENTTYPECONTAINER, Asset],
    [c.TYPES.DATADEFINITION, Asset],
    [c.TYPES.DATADEFINITIONCONTAINER, Asset],
    [c.TYPES.DESTINATION, Asset],
    [c.TYPES.FACEBOOKCONNECTOR, Asset],
    [c.TYPES.FEEDBLOCK, Asset],
    [c.TYPES.FILE, Asset],
    [c.TYPES.FOLDER, Asset],
    [c.TYPES.GOOGLEANALYTICSCONNECTOR, Asset],
    [c.TYPES.GROUP, Asset],
    [c.TYPES.INDEXBLOCK, Asset],
    [c.TYPES.METADATASET, Asset],
    [c.TYPES.METADATASETCONTAINER, Asset],
    [c.TYPES.PAGE, Page],
    [c.TYPES.PAGECONFIGURATIONSET, Asset],
    [c.TYPES.PAGECONFIGURATIONSETCONTAINER, Asset],
    [c.TYPES.PUBLISHSET, Asset],
    [c.TYPES.PUBLISHSETCONTAINER, Asset],
    [c.TYPES.REFERENCE, Asset],
    [c.TYPES.ROLE, Asset],
    [c.TYPES.SCRIPTFORMAT, Asset],
    [c.TYPES.SHAREDFIELD, Asset],
    [c.TYPES.SHAREDFIELDCONTAINER, Asset],
    [c.TYPES.SITE, Asset],
    [c.TYPES.SITEDESTINATIONCONTAINER, Asset],
    [c.TYPES.SYMLINK, Asset],
    [c.TYPES.TEMPLATE, Asset],
    [c.TYPES.TEXTBLOCK, Asset],
    [c.TYPES.TRANSPORTCLOUD, Asset],
    [c.TYPES.TRANSPORTDB, Asset],
    [c.TYPES.TRANSPORTFS, Asset],
    [c.TYPES.TRANSPORTFTP, Asset],
    [c.TYPES.TRANSPORTCONTAINER, Asset],
    [c.TYPES.TWITTERCONNECTOR, Asset],
    [c.TYPES.USER, Asset],
    [c.TYPES.WORDPRESSCONNECTOR, Asset],
    [c.TYPES.WORKFLOWDEFINITION, Asset],
    [c.TYPES.WORKFLOWDEFINITIONCONTAINER, Asset],
    [c.TYPES.WORKFLOWEMAIL, Asset],
    [c.TYPES.WORKFLOWEMAILCONTAINER, Asset],
    [c.TYPES.XHTMLDATADEFINITIONBLOCK, Asset],
    [c.TYPES.XMLBLOCK, Asset],
    [c.TYPES.XSLTFORMAT, Asset]
])